Using traditional method to scrape rather than ATDIS
planningalerts-scrapers/maitland pull request #2
Opened 2016-09-16 13:26 UTC by LoveMyData

Traditional method to scrape is pretty easy because this site support XML, it is almost as good as ATDIS

2016-09-19 01:06 UTC, equivalentideas commented on scraper.rb
> +page = agent.get(base_url)
Why you need to request this page here, and then overwrite it immediately?

2016-09-19 01:06 UTC, equivalentideas commented on scraper.rb
> +  record["info_url"]          = base_url
Shame we can't get a better info_url, but I can't see a way to get it in there system.

2016-09-19 01:10 UTC, equivalentideas commented on scraper.rb
> +  record = {}
You could make this assignment more succinct like https://github.com/planningalerts-scrapers/canterbury/blob/master/scraper.rb#L23-L31

2016-09-19 01:13 UTC, equivalentideas commented on scraper.rb
> +  if ( !record.has_blank? )
What could be blank here? PlanningAlerts will do some validation on it's end to not include applications that don't meet it's needs. Not sure if you need this.

Also, this might be clearer as `unless record.has_blank?` :)

2016-09-19 01:14 UTC, equivalentideas requested changes
Looking Good @LoveMyData . I've left some questions and feedback here.

2016-09-19 02:17 UTC, LoveMyData commented on scraper.rb
> +page = agent.get(base_url)
Cookie...  I think the first one will have all the cookie info and the second get will use previously saved cookie and make a second request.

2016-09-19 02:20 UTC, LoveMyData commented on scraper.rb
> +  record = {}
ok, just a matter of getting used to Ruby's syntax, the way I current have, anyone without Ruby background will understand... I think...

2016-09-19 02:20 UTC, LoveMyData commented on scraper.rb
> +  record["info_url"]          = base_url
Cookie pain..!!

2016-09-19 02:24 UTC, LoveMyData commented on scraper.rb
> +  if ( !record.has_blank? )
Address field could be blank and I figured out if there is no address, no point to even saved to the DB. Go to the DA web site and click on 'Last Month' and you will see the entries like below

![image](https://cloud.githubusercontent.com/assets/15683093/18621248/ab218890-7e63-11e6-8127-61c56f560089.png)

2016-09-19 02:44 UTC, LoveMyData commented
@equivalentideas, I have tried all of the code you suggested, broke a lot of things... 

With my very limited knowledge with Ruby, can't fix any of your request at the moment.
Hash/array is broken, using 'unless' now it is complaint #has_blank is not found. Feel free to make any changes

2016-09-21 01:45 UTC, equivalentideas commented on scraper.rb
> +  if ( !record.has_blank? )
Nice one, that makes sense. According to our spec:

> The following fields are required. All development applications should have these bits of information.

So totally makes sense to drop applications that have no address.

I think rather than this catch all `has_blank?` it could be better to be specific with something like `unless record["address"].empty?` so it’s clear exactly what’s being tested.

2016-09-21 01:53 UTC, equivalentideas commented on scraper.rb
> +  record = {}
That's fair enough. If you do wanna try changing this it would be:

```
 record = {
  "council_reference": r.at("AccountNumber")["org_value"],
  "address": r.at("Property")["org_value"],
  "description": r.at("Description")["org_value"],
  "info_url": base_url,
  "comment_url": comment_url,
  "date_scraped": Date.today.to_s,
  "date_received": Date.strptime(r.at("Lodged")["org_value"], '%d/%m/%Y').to_s
}
```

You could go without the "":

```
 record = {
  council_reference: r.at("AccountNumber")["org_value"],
```

And then refer to these keys in the format `record[:council_reference]`. Whatever feels best to you.

2016-09-21 01:55 UTC, equivalentideas commented
Good work trying these @LoveMyData , I've left some comments with some help. Paste in here the change you made, maybe I can see what's breaking?

2016-09-21 02:30 UTC, LoveMyData commented
@equivalentideas https://gist.github.com/LoveMyData/eba9a43e3970fb8af44b2da6e53f33d9

2016-09-21 02:34 UTC, LoveMyData commented on scraper.rb
> +  if ( !record.has_blank? )
'record' only contain all the required fields, so it make sense to 'test' all condition, rather than 'address'.

2016-09-21 03:03 UTC, equivalentideas commented on scraper.rb
> +  if ( !record.has_blank? )
That's a good point 👍  sounds good to me then. You should still be able to make it:

```
unless record.has_blank?
  ...
end
```

2016-09-22 02:13 UTC, LoveMyData commented on scraper.rb
> +  if ( !record.has_blank? )
@equivalentideas updated to use unless in the latest commit

2016-09-30 09:02 UTC, equivalentideas commented
Looks great @LoveMyData well done with Ruby :) I added a commit to add "NSW" to the addresses, as [the guide](https://www.planningalerts.org.au/how_to_write_a_scraper) recommends:

>  If the original address did not include the state (e.g. "QLD") at the end, then add it.

2016-09-30 09:02 UTC, equivalentideas approved these changes

2016-09-30 09:02 UTC, merged